export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./pages/Home";
export { default as About } from "./pages/About";
export { default as Blog } from "./pages/Blog";
export { default as Contact } from "./pages/Contact";
export { default as WebDev } from "./pages/WebDev";
export { default as Essays } from "./pages/Essays";
export { default as Podcasts } from "./pages/Podcasts";